import BN from "bn.js";
import { Polynomial, ScopedStore, ShareStore, ShareStoreMap, ShareStorePolyIDShareIndexMap } from "./base";
import { CatchupToLatestShareResult, GenerateNewShareResult, InitializeNewKeyResult, IThresholdBak, IThresholdBakApi, KeyDetails, ModuleMap, RefreshMiddlewareMap, RefreshSharesResult, ThresholdBakArgs } from "./baseTypes/aggregateTypes";
import { BNString, IServiceProvider, IStorageLayer, PolynomialID, StringifiedType } from "./baseTypes/commonTypes";
import Metadata from "./metadata";
declare class ThresholdBak implements IThresholdBak {
    modules: ModuleMap;
    enableLogging: boolean;
    serviceProvider: IServiceProvider;
    storageLayer: IStorageLayer;
    shares: ShareStorePolyIDShareIndexMap;
    privKey: BN;
    metadata: Metadata;
    refreshMiddleware: RefreshMiddlewareMap;
    storeDeviceShare: (deviceShareStore: ShareStore) => Promise<void>;
    constructor(args?: ThresholdBakArgs);
    getApi(): IThresholdBakApi;
    initialize(input?: ShareStore): Promise<KeyDetails>;
    private initializeModules;
    catchupToLatestShare(shareStore: ShareStore): Promise<CatchupToLatestShareResult>;
    reconstructKey(): Promise<BN>;
    reconstructLatestPoly(): Polynomial;
    generateNewShare(): Promise<GenerateNewShareResult>;
    refreshShares(threshold: number, newShareIndexes: Array<string>, previousPolyID: PolynomialID): Promise<RefreshSharesResult>;
    initializeNewKey({ userInput, initializeModules }: {
        userInput?: BN;
        initializeModules?: boolean;
    }): Promise<InitializeNewKeyResult>;
    inputShare(shareStore: ShareStore): void;
    inputShareSafe(shareStore: ShareStore): Promise<void>;
    outputShare(shareIndex: BNString): ShareStore;
    setKey(privKey: BN): void;
    getKeyDetails(): KeyDetails;
    syncShareMetadata(adjustScopedStore?: (ss: ScopedStore) => ScopedStore): Promise<void>;
    syncSingleShareMetadata(share: BN, adjustScopedStore?: (ss: ScopedStore) => ScopedStore): Promise<void>;
    addRefreshMiddleware(moduleName: string, middleware: (generalStore: unknown, oldShareStores: ShareStoreMap, newShareStores: ShareStoreMap) => unknown): void;
    setDeviceStorage(storeDeviceStorage: (deviceShareStore: ShareStore) => Promise<void>): void;
    addShareDescription(shareIndex: string, description: string, updateMetadata?: boolean): Promise<void>;
    deleteShareDescription(shareIndex: string, description: string, updateMetadata?: boolean): Promise<void>;
    toJSON(): StringifiedType;
    static fromJSON(value: StringifiedType, args: ThresholdBakArgs): Promise<ThresholdBak>;
}
export default ThresholdBak;
